name: learningbubbles
description: A new Flutter project for Learning Bubbles.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.0.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  flutter_riverpod: ^2.5.1
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  flutter_timezone: ^1.0.8
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
